[book]
authors = ["ZigCC"]
language = "en"
multilingual = false
src = "book-src"
title = "Zig cookbook"

[output.html]
git-repository-url = "https://github.com/zigcc/zig-cookbook"
edit-url-template = "https://github.com/zigcc/zig-cookbook/edit/main/{path}"
additional-js = ["theme/zigLanguageSupport.js"]